baseURL = "/"
languageCode = "en-us"
title = "Donald Obi - Web Development & Design Portfolio"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Portfolio"
    url = "/#portfolio"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 3

[params]
  description = "Website development and design projects by Donald Obi"
  author = "Donald Obi"